@startuml
'https://plantuml.com/class-diagram

class javafx.App {
    start()
    main()
}

class Item {
    String name
    String serialNumber
    BigDecimal price

    get()
    set()
    toString()
}

class FileLoader {
    File file
    ObservableList list

    readFromTXT()
    readFromHTML()
    readFromJSON()

}

class FileSaver {
    File file
    ObservableList list

    readToTxt()
    readToHTML()
    readToJSON()

}

class InventoryController {
    ObservableList inventoryList
}

javafx.App*--InventoryController
InventoryController--FileLoader
InventoryController--Item
InventoryController--FileSaver

@enduml